### ISSUE TITLE
I have some new ideas

### ISSUE THREAD

**Issue by HermitAssociation** [hax0r31337/re1999-tools#1]
Have you tried to decrypt the cinfigs folder?

**Comment by hax0r31337** [comment]
Yes I tried, for files with GZip header, it's not encrypted at all, and the other files can be decrypted with `text-assets.py`

**Comment by HermitAssociation** [comment]
So, does the configs folder contain all the json data in the game? I still have some questions that I don't quite understand. Can we discuss this in detail through some other software like Discrod?

**Comment by hax0r31337** [comment]
> So, does the configs folder contain all the json data in the game? I still have some questions that I don't quite understand. Can we discuss this in detail through some other software like Discrod?

Sure, please leave your discord username here

**Comment by HermitAssociation** [comment]
hermitisla，thank you!
